version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: tamtruong9228/circleci-demo
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:ab:18:62:1c:72:db:fe:76:f1:ae:69:d5:7a:ff:65"
      - run: ssh -oStrictHostKeyChecking=no -v circleci@192.168.1.121 './deploy.sh'

workflows:
  first-demo:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build-and-push
        